In [1]:
import torch

print(torch.__version__)

2.6.0


In [10]:
# Creating the empty torch or tensor
x = torch.empty(2,dtype=torch.int)
print(x)

# Two dimentional Tensor
y = torch.empty(size=(5, 3), dtype=torch.float16)
print(y)

tensor([0, 0], dtype=torch.int32)
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float16)


In [37]:
a = torch.tensor([11, 4, 23])
b = torch.tensor([24, 5, 23])

print(a)
print(a + b)
print(a - b)


A = torch.rand(3, 3)
B = torch.rand(3,3)

print(A.mm(B))

A.add_(B)

print(A)

tensor([11,  4, 23])
tensor([35,  9, 46])
tensor([-13,  -1,   0])
tensor([[1.0292, 0.3589, 0.6312],
        [0.5949, 0.1991, 0.5598],
        [0.7166, 0.1973, 0.0475]])
tensor([[1.1362, 0.6210, 1.1084],
        [1.2096, 0.5912, 0.5903],
        [0.9710, 0.2413, 0.7760]])
